# Generated by Django 5.1.5 on 2025-01-31 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogRatingLeakyBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_size', models.IntegerField(default=0)),
                ('bucket_capacity', models.IntegerField(default=0)),
                ('leak_rate', models.IntegerField(default=1000)),
                ('last_record', models.TimeField(auto_now_add=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaky_bucket', to='blog_posts.blogpost')),
            ],
        ),
    ]
