# Generated by Django 5.1.5 on 2025-01-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0004_alter_blogratingleakybucket_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogratingleakybucket',
            name='last_record',
            field=models.FloatField(),
        ),
    ]
