# Generated by Django 5.1.5 on 2025-01-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0005_alter_blogratingleakybucket_last_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogratingleakybucket',
            name='bucket_capacity',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='blogratingleakybucket',
            name='leak_rate',
            field=models.IntegerField(default=100),
        ),
    ]
