# Generated by Django 5.1.5 on 2025-02-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0006_alter_blogratingleakybucket_bucket_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogratingleakybucket',
            name='bucket_capacity',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='blogratingleakybucket',
            name='leak_rate',
            field=models.IntegerField(default=10),
        ),
    ]
