# Generated by Django 5.1.5 on 2025-02-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0007_alter_blogratingleakybucket_bucket_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogratingleakybucket',
            name='last_record',
            field=models.IntegerField(),
        ),
    ]
