# Generated by Django 5.1.5 on 2025-02-03 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0008_alter_blogratingleakybucket_last_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogRatingEma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_request_rate', models.FloatField(default=0)),
                ('mean_request_rate', models.FloatField(default=0)),
                ('variation_sum', models.FloatField(default=0)),
                ('last_record', models.FloatField()),
                ('blog_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ema', to='blog_posts.blogpost')),
            ],
        ),
    ]
